accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
]

dashboard/urls.py
from django.urls import path, include
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index')
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing_page.urls', namespace='landing_page')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landing_page/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass


class NewsletterSub(models.Model):
    is_active = models.BooleanField(default=True)
    email = models.EmailField(max_length=300)
    created_at = models.DateTimeField(auto_now_add=True)

common/models/image.py
import uuid

from django.db import models
from thumbnails.fields import ImageField
 
# Create your models here.


class Image(models.Model):
    image = ImageField(pregenerated_sizes=["small", "large"], upload_to="images")
    name = models.CharField(max_length=256, default="")
    uuid = models.UUIDField(auto_created=True, unique=True, null=True, blank=True)

    def __str__(self):
        return f"{self.name} |  {self.id}"
    
    def save(self, *args, **kwargs):
        created = not self.pk

        if created:
            self.uuid = uuid.uuid4()
    
        return super(Image, self).save(args, kwargs)

order/models.py
from django.db import models

# Create your models here.

product/models/price.py
from django.db import models

class Price(models.Model):

    class Currency(models.IntegerChoices):
        RUPEES = 0

    min_price = models.IntegerField(help_text="Min price for product")
    max_price = models.IntegerField(help_text="Max price for product")
    currency = models.IntegerField(choices=Currency, default=Currency.RUPEES)

product/models/product.py
from django.db import models


from common.models import Image
from product.models import Price


class Product(models.Model):
    is_active = models.BooleanField(default=True, help_text="Is product active.")
    price = models.ForeignKey(Price, on_delete=models.SET_NULL, null=True, blank=True)
    image = models.ForeignKey(Image, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=126)
    description = models.TextField()


    def __str__(self):
        return f"{self.name} | {self.id}"

product/models/rating.py
from django.db import models

from product.models import Product

class Rating(models.Model):
    number = models.IntegerField(default=0)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.product.name} | {self.id}"

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User
from django import forms
class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class LoginForm(forms.Form):
    username = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse

from .forms import CustomUserCreationForm, LoginForm
from .models import User

# Create your views here.
def login_view(request):

    #prevents access by logged in users
    if request.user.is_authenticated:
        return redirect('dashboard:index')

    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():    
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('dashboard:index')
            else:
                return render(request, 'accounts/login.html', {
                    'message': 'Invalid username and/or password'
                })
        else:
            pass
    elif request.method == 'GET':
        form = LoginForm()
        return render(request, 'accounts/login.html', {"form": form})

def logout_view(request):
    logout(request)
    return redirect('accounts:login')

def register_view(request):

    #prevents access by logged in users
    if request.user.is_authenticated:
        return redirect('dashboard:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('dashboard:index')
        else:
            #checks if username is taken
            username = request.POST['username']
            if User.objects.filter(username=username).exists():
                return render(request, 'accounts/register.html', {
                    'form': form,
                    'message': 'Username has already been taken'
                })
            #checks if email is taken
            email = request.POST['email']
            if User.objects.filter(email=email).exists():
                return render(request, 'accounts/register.html', {
                    'form': form,
                    'message': 'Email address is already in use'
                })
            password1 = request.POST['password1']
            confirm = request.POST['password2']
            if password1 != confirm:
                return render(request, 'accounts/register.html', {
                    'form': form,
                    'message': 'Passwords do not match'
                })

            return render(request, 'accounts/register.html', {
                'form': form,
                'message': 'An unknown error occured.'
                })
    elif request.method == 'GET':
        form = CustomUserCreationForm()
        return render(request, 'accounts/register.html', {'form': form})

common/views.py
from django.shortcuts import render

# Create your views here.

dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):

    #if user is not logged in, redirect to home page
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    
    return render(request, 'dashboard/index.html')

landing_page/views.py
from django.shortcuts import render

from product.models import Product
# Initial landing page view.
def index(request):

    products = Product.objects.all()

    return render(request, 'landing_page/index.html', {"products": products})


#Add other views here

order/views.py
from django.shortcuts import render

# Create your views here.

product/views.py
from django.shortcuts import render

# Create your views here.

accounts/templates/accounts/login.html
{% extends 'base/base.html' %}
{% load form_tags %}
{% load static %}


{% block title %}Register{% endblock title %}

{% block content %}
    <form action="{% url 'accounts:login' %}" method="post" class="max-w-lg mx-auto p-6 bg-white rounded-lg shadow-lg dark:bg-gray-800 my-5">
        {% csrf_token %}

        <h1 class="text-3xl font-bold mb-6 text-gray-900 dark:text-white">Log In</h1>

        {% if message %}
            <p class="mb-4 text-red-500">{{ message }}</p>
        {% endif %}

        {% for field in form %}
            <div class="form-group mb-4">
                <!-- Field Label -->
                <label for="{{ field.id_for_label }}" class="block text-gray-700 dark:text-gray-300 mb-2">
                    {{ field.label }}
                </label>

                <!-- Field Input -->
                {{ field|add_class:"w-full p-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:text-gray-300" }}

                <!-- Field Errors -->
                {% if field.errors %}
                    <p class="text-red-500 mt-2 text-sm">
                        {{ field.errors.as_text|escape }}
                    </p>
                {% endif %}
            </div>
        {% endfor %}

        <!-- Submit Button -->
        <input type="submit" value="Sign Up"
            class="w-full bg-blue-600 text-white py-2 px-4 rounded-lg hover:bg-blue-700 transition dark:bg-blue-500 dark:hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500">

        <!-- Login Link -->
        <p class="mt-4 text-gray-600 dark:text-gray-400">
            Don't have account?  <a href="{% url 'accounts:register' %}" class="text-blue-600 dark:text-blue-400 hover:underline">Create One.</a>
        </p>
    </form>

   
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base/base.html' %}
{% load form_tags %}
{% load static %}


{% block title %}Register{% endblock title %}

{% block content %}
    <form action="{% url 'accounts:register' %}" method="post" class="max-w-lg mx-auto p-6 bg-white rounded-lg shadow-lg dark:bg-gray-800 my-5">
        {% csrf_token %}

        <h1 class="text-3xl font-bold mb-6 text-gray-900 dark:text-white">Register</h1>

        {% if message %}
            <p class="mb-4 text-red-500">{{ message }}</p>
        {% endif %}

        {% for field in form %}
            <div class="form-group mb-4">
                <!-- Field Label -->
                <label for="{{ field.id_for_label }}" class="block text-gray-700 dark:text-gray-300 mb-2">
                    {{ field.label }}
                </label>

                <!-- Field Input -->
                {{ field|add_class:"w-full p-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:text-gray-300" }}

                <!-- Field Errors -->
                {% if field.errors %}
                    <p class="text-red-500 mt-2 text-sm">
                        {{ field.errors.as_text|escape }}
                    </p>
                {% endif %}
            </div>
        {% endfor %}

        <!-- Submit Button -->
        <input type="submit" value="Sign Up"
            class="w-full bg-blue-600 text-white py-2 px-4 rounded-lg hover:bg-blue-700 transition dark:bg-blue-500 dark:hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500">

        <!-- Login Link -->
        <p class="mt-4 text-gray-600 dark:text-gray-400">
            Already have an account? <a href="{% url 'accounts:login' %}" class="text-blue-600 dark:text-blue-400 hover:underline">Login here.</a>
        </p>
    </form>

   
{% endblock %}

dashboard/templates/dashboard/base.html
{% load static %}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% tailwind_css %} 
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'landing_page/images/favicon.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'landing_page/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'dashboard/css/dashboard.css' %}">
    <title>dashboard</title>
</head>
<body>
    {% block content %}
    {% endblock content %}
</body>
</html>

dashboard/templates/dashboard/index.html
{% extends 'dashboard/base.html' %}
{% load static %}


{% block content %}

<h1>Hi there, <strong>{{request.user}}</strong>. Welcome to the dashboard</h1>

This is a blank dashboard page which inherits from dashboard/base.html. It has seperate CSS from the landing page and is located at <strong>dashboard/static/dashboard/css/dashboard.css</strong>

<p><strong style="color:red;">Note: this page is login restricted and can only be accessed by logged in users.</strong></p>

<h2>Instructions</h2>

<ol>
    <li>
        There is one CSS file in this app - <strong>dashboard.css</strong>. Feel free to replace this CSS with your own custom CSS
    </li>
</ol>

<p>To log out, click <a href="{% url 'accounts:logout' %}">here</a></p>


{% endblock content %}

templates/base/base.html
{% load static %}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% tailwind_css %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/flowbite@2.5.1/dist/flowbite.min.css" rel="stylesheet" />
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/base/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/base/index.css' %}">
    <title></title>
</head>
<body>
    {% include 'base/navbar.html' %}
    {% block content %}
    {% endblock content %}
    {% include 'base/footer.html' %}
    <script src="{% static 'js/index.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js"></script>
</body>
</html>

templates/base/footer.html
<!-- footer.html -->
<footer class="bg-amber-50 text-amber-900 py-8">
    <div class="max-w-7xl mx-auto grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 px-4">
        <!-- About Us -->
        <div>
            <h3 class="text-lg font-semibold mb-3">About Us</h3>
            <p class="text-sm">
                We provide the highest quality dry fruits with fast home delivery across India. Freshness guaranteed!
            </p>
        </div>

        <!-- Our Products -->
        <div>
            <h3 class="text-lg font-semibold mb-3">Our Products</h3>
            <ul class="text-sm space-y-2">
                <li><a href="" class="hover:underline">Cashews</a></li>
                <li><a href="" class="hover:underline">Walnuts</a></li>
                <li><a href="" class="hover:underline">Peanuts</a></li>
                <li><a href="" class="hover:underline">Mixed Dry Fruits</a></li>
            </ul>
        </div>

        <!-- Customer Support -->
        <div>
            <h3 class="text-lg font-semibold mb-3">Customer Support</h3>
            <ul class="text-sm space-y-2">
                <li><a href="" class="hover:underline">FAQs</a></li>
                <li><a href="" class="hover:underline">Return Policy</a></li>
                <li><a href="" class="hover:underline">Delivery Information</a></li>
            </ul>
        </div>

        <!-- Connect with Us -->
        <div>
            <h3 class="text-lg font-semibold mb-3">Connect with Us</h3>
            <div class="flex space-x-4 mb-4">
                <a href="https://instagram.com/wealth_dryfruits" class="text-black hover:text-black">
                    <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
                        <path fill-rule="evenodd" d="M13.135 6H15V3h-1.865a4.147 4.147 0 0 0-4.142 4.142V9H7v3h2v9.938h3V12h2.021l.592-3H12V6.591A.6.6 0 0 1 12.592 6h.543Z" clip-rule="evenodd"/>
                      </svg>                      
                </a>
                <a href="https://instagram.com/wealth_dryfruits" class="hover:text-amber-600">
                    <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                        <path fill="currentColor" fill-rule="evenodd" d="M3 8a5 5 0 0 1 5-5h8a5 5 0 0 1 5 5v8a5 5 0 0 1-5 5H8a5 5 0 0 1-5-5V8Zm5-3a3 3 0 0 0-3 3v8a3 3 0 0 0 3 3h8a3 3 0 0 0 3-3V8a3 3 0 0 0-3-3H8Zm7.597 2.214a1 1 0 0 1 1-1h.01a1 1 0 1 1 0 2h-.01a1 1 0 0 1-1-1ZM12 9a3 3 0 1 0 0 6 3 3 0 0 0 0-6Zm-5 3a5 5 0 1 1 10 0 5 5 0 0 1-10 0Z" clip-rule="evenodd"/>
                      </svg>                      
                </a>
            </div>

            <!-- Newsletter Signup -->
            <form method="POST" action="">
                {% csrf_token %}
                <div class="flex space-x-2">
                    <input type="email" name="email" placeholder="Enter your email" class="px-4 py-2 bg-white border border-amber-300 rounded-md focus:outline-none focus:ring-2 focus:ring-amber-500 text-sm w-full">
                    <button type="submit" class="bg-amber-600 text-white px-4 py-2 rounded-md text-sm hover:bg-amber-700">
                        Subscribe
                    </button>
                </div>
            </form>
        </div>
    </div>

    <!-- Footer Bottom -->
    <div class="border-t mt-6 pt-4 text-center text-sm text-amber-700">
        <p>&copy; {{ current_year }} Dry Fruits Co. All rights reserved.</p>
    </div>
</footer>

templates/base/navbar.html
{% load static %}
<nav class="dark border-gray-200 dark:bg-gray-900 dark:border-gray-700">
    <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
        <a href="#" class="flex items-center space-x-3 rtl:space-x-reverse">
            <img src="{% static 'images/favicon.png' %}" class="h-8" alt="Flowbite Logo" />
            <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">W</span>
        </a>
        <button data-collapse-toggle="navbar-multi-level" type="button"
            class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
            aria-controls="navbar-multi-level" aria-expanded="false">
            <span class="sr-only">Open main menu</span>
            <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M1 1h15M1 7h15M1 13h15" />
            </svg>
        </button>
        <div class="hidden w-full md:block md:w-auto" id="navbar-multi-level">
            <ul
                class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
                <li>
                    <a href="{% url 'landing_page:index' %}"
                        class="block py-2 px-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 md:dark:text-blue-500 dark:bg-blue-600 md:dark:bg-transparent"
                        aria-current="page">Home</a>
                </li>
                {% if request.user.is_authenticated %}
                    <li>
                        <a href="#"
                            class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Your Orders</a>
                    </li>
                    <li>
                        <button id="dropdownNavbarLink" data-dropdown-toggle="dropdownNavbar"
                            class="flex items-center justify-between w-full py-2 px-3 text-gray-900 hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 md:w-auto dark:text-white md:dark:hover:text-blue-500 dark:focus:text-white dark:hover:bg-gray-700 md:dark:hover:bg-transparent">My
                            Account
                            <svg class="w-2.5 h-2.5 ms-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                                fill="none" viewBox="0 0 10 6">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="m1 1 4 4 4-4" />
                            </svg></button>
                        <!-- Dropdown menu -->
                        <div id="dropdownNavbar"
                            class="z-10 hidden font-normal bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 dark:divide-gray-600">
                            <ul class="py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownLargeButton">
                                <li>
                                    <a href="#"
                                        class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">
                                        Profile</a>
                                </li>
                                <li>
                                    <a href="#"
                                        class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Earnings</a>
                                </li>
                            </ul>
                            <div class="py-1">
                                <a href="#"
                                    class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Sign
                                    out</a>
                            </div>
                        </div>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'accounts:register' %}"
                            class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Register</a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:login' %}"
                            class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Login In</a>
                    </li>
                {% endif %}
                <li>
                    <a href="#"
                        class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Contact</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/landing_page/index.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
    <!-- Banner Section with Animation -->
    <header class="relative bg-cover bg-center bg-no-repeat h-screen flex flex-col justify-center items-center text-white w-full"
        style="background-image: url('https://dnl7nif3s8j3b.cloudfront.net/static/images/banner.webp'); background-position: center;background-repeat: no-repeat;">
        <div class="bg-slate-600 bg-opacity-50 p-8 rounded-lg animate__animated animate__fadeInDown text-center">
            <h1 class="text-5xl font-extrabold drop-shadow-lg">Welcome to Wealth Dry Fruits</h1>
            <p class="mt-4 text-xl mx-auto">Premium quality dry fruits for a healthier lifestyle.</p>
            <a href="#products" class="mt-6 inline-block bg-yellow-500 text-black font-semibold py-3 px-8 rounded-full hover:bg-yellow-600 transition duration-300 transform hover:scale-105 animate__animated animate__pulse">Shop Now</a>
        </div>
        <!-- Scroll Down Arrow -->
        <a href="#products" class="absolute bottom-10 text-black text-3xl animate__animated animate__bounce">
            &#x2193;
        </a>
    </header>

    <!-- Product Section with Animation -->
    <section id="products" class="py-16 fade-in">
        <div class="container mx-auto">
            <h2 class="text-4xl font-bold text-center mb-12 text-gray-800 animate__animated animate__fadeInUp">Our Best Sellers</h2>

            <div class="flex justify-evenly gap-4 items-center flex-wrap">
                <!-- Loop through products -->
                {% for product in products %}
                <div class="bg-white shadow-lg rounded-lg p-6 mx-4 transform hover-grow transition duration-300 animate__animated animate__fadeInUp">
                    <img src="{{ product.image.image.thumbnails.small.url }}" alt="{{ product.name }}" class="w-full h-18 object-cover rounded-lg">
                    <div class="p-4">
                        <h3 class="text-2xl font-semibold text-gray-700">{{ product.name }}</h3>
                        <p class="text-gray-600 mt-2">{{ product.description | truncatewords:4}}</p>
                        <div class="mt-6 flex justify-between items-center flex-col">
                            <p class="text-lg font-bold text-orange-700">₹ {{ product.price.min_price }}</p>
                            <button class="bg-orange-300 text-white py-2 px-4 rounded-full hover:bg-green-600 transition duration-300" 
                                onclick="addToCart({{ product.id }})">Add to Cart</button>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>

    <!-- Cart Icon (Fixed to Bottom) with Animation -->
    <div class="fixed bottom-6 right-6 animate__animated animate__fadeInRight">
        <a href="" class="relative">
            <div class="bg-green-700 text-white p-4 rounded-full shadow-lg hover:bg-green-800 transition duration-300 transform hover:scale-110">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2m3.6 0h10l1.68 7.02M16 13h-4m-4 0H7l-4 9h18l-1.72-7.02M5 18h14M9 22a2 2 0 100-4 2 2 0 000 4zm6-2a2 2 0 11-4 0 2 2 0 014 0z" />
                </svg>
            </div>
            <!-- Cart Item Count -->
            <span class="absolute top-0 right-0 inline-block w-5 h-5 bg-red-600 text-white text-xs text-center rounded-full">0</span>
        </a>
    </div>
    <!-- Whatsapp Icon (Fixed to Bottom) with Animation -->
    <div class="fixed bottom-24 right-6 animate__animated animate__fadeInRight">
        <a href="{{request.WHATSAPPURL}}"
            " class="relative">
            <div class="bg-green-700 text-white p-4 rounded-full shadow-lg hover:bg-green-800 transition duration-300 transform hover:scale-110">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 48 48">
                    <path fill="#25D366" d="M23.999 0C10.746 0 0 10.746 0 24c0 4.171 1.073 8.14 3.106 11.697L0 48l12.612-3.102A23.926 23.926 0 0 0 24 48c13.255 0 24-10.746 24-24S37.255 0 24 0Zm-.001 44.063a20.983 20.983 0 0 1-10.701-2.954l-.768-.457-7.475 1.838 1.942-7.285-.5-.787A20.946 20.946 0 0 1 3.001 24.001c0-11.598 9.401-21 21-21 11.597 0 21 9.402 21 21 0 11.599-9.402 21.001-21.003 21.001Z"/>
                    <path fill="#25D366" d="M36.33 31.601c-.561-.28-3.296-1.63-3.805-1.822-.511-.188-.882-.28-1.255.281-.373.562-1.439 1.82-1.764 2.191-.328.373-.648.415-1.206.14-.561-.28-2.364-.867-4.51-2.759-1.667-1.485-2.787-3.319-3.116-3.879-.329-.562-.034-.867.248-1.148.254-.253.56-.66.841-.99.282-.329.374-.561.561-.934.19-.374.095-.701-.048-.981-.14-.281-1.255-3.03-1.725-4.163-.451-1.086-.907-.939-1.255-.955-.327-.014-.702-.017-1.073-.017-.374 0-.98.14-1.491.701-.514.561-1.94 1.899-1.94 4.635 0 2.735 1.986 5.384 2.264 5.762.28.373 3.906 6.017 9.456 8.44.301.13.535.205.717.263.302.096.575.083.792.048.242-.035 2.365-.966 3.255-2.705.096-.186.095-.373.048-.562-.051-.184-.188-.28-.395-.373Z"/>
                  </svg>
            </div>
            <!-- Cart Item Count -->
            <span class="absolute top-0 right-0 inline-block w-5 h-5 bg-red-600 text-white text-xs text-center rounded-full">0</span>
        </a>
    </div>
{% endblock content %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>